// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ScienceAndMaths_MachineLearning
{
    public partial class AgbarMLModelFull
    {
        /// <summary>
        /// model input class for AgbarMLModelFull.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Census_section")]
            public string Census_section { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Month")]
            public string Month { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Day_of_week")]
            public string Day_of_week { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Normalized_Consumption")]
            public float Normalized_Consumption { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Population_higher16_rate")]
            public float Population_higher16_rate { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Population_highschool_rate")]
            public float Population_highschool_rate { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Housing_biggerSize_rate")]
            public float Housing_biggerSize_rate { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"PERCENTAGE_RESERVOIR")]
            public float PERCENTAGE_RESERVOIR { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"income_percapita")]
            public float Income_percapita { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for AgbarMLModelFull.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Census_section")]
            public float[] Census_section { get; set; }

            [ColumnName(@"Month")]
            public float[] Month { get; set; }

            [ColumnName(@"Day_of_week")]
            public float[] Day_of_week { get; set; }

            [ColumnName(@"Normalized_Consumption")]
            public float Normalized_Consumption { get; set; }

            [ColumnName(@"Population_higher16_rate")]
            public float Population_higher16_rate { get; set; }

            [ColumnName(@"Population_highschool_rate")]
            public float Population_highschool_rate { get; set; }

            [ColumnName(@"Housing_biggerSize_rate")]
            public float Housing_biggerSize_rate { get; set; }

            [ColumnName(@"PERCENTAGE_RESERVOIR")]
            public float PERCENTAGE_RESERVOIR { get; set; }

            [ColumnName(@"income_percapita")]
            public float Income_percapita { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AgbarMLModelFull.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
