// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ScienceAndMaths_MachineLearning
{
    public partial class AgbarMLModel1
    {
        /// <summary>
        /// model input class for AgbarMLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Dia_semana")]
            public float Dia_semana { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Mes")]
            public float Mes { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Año")]
            public float Año { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Census_section")]
            public float Census_section { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Postcode")]
            public float Postcode { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Consumption")]
            public float Consumption { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for AgbarMLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Dia_semana")]
            public float Dia_semana { get; set; }

            [ColumnName(@"Mes")]
            public float Mes { get; set; }

            [ColumnName(@"Año")]
            public float Año { get; set; }

            [ColumnName(@"Census_section")]
            public float Census_section { get; set; }

            [ColumnName(@"Postcode")]
            public float Postcode { get; set; }

            [ColumnName(@"Consumption")]
            public float Consumption { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AgbarMLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
