// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ScienceAndMaths_MachineLearning
{
    public partial class AgbarMLModelBasic
    {
        /// <summary>
        /// model input class for AgbarMLModelBasic.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Postcode")]
            public string Postcode { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Year")]
            public float Year { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Month")]
            public string Month { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Day_of_week")]
            public string Day_of_week { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Average_Consumption")]
            public float Average_Consumption { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for AgbarMLModelBasic.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Postcode")]
            public float[] Postcode { get; set; }

            [ColumnName(@"Year")]
            public float Year { get; set; }

            [ColumnName(@"Month")]
            public float[] Month { get; set; }

            [ColumnName(@"Day_of_week")]
            public float[] Day_of_week { get; set; }

            [ColumnName(@"Average_Consumption")]
            public float Average_Consumption { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AgbarMLModelBasic.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
